// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE7j0wbmL2eL_G1w7hVNBynW3qTZK4MdM',
    appId: '1:229438324185:web:3aaff666aed5a1f4a4adc8',
    messagingSenderId: '229438324185',
    projectId: 'upkeep-1658b',
    authDomain: 'upkeep-1658b.firebaseapp.com',
    storageBucket: 'upkeep-1658b.appspot.com',
    measurementId: 'G-255YNRH1LJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEPNhN87OuJlEeTU1MoLCaVJgPl0CfLZs',
    appId: '1:229438324185:android:d894f1e7604c8267a4adc8',
    messagingSenderId: '229438324185',
    projectId: 'upkeep-1658b',
    storageBucket: 'upkeep-1658b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRGZvw4v5FDONPA-s9KACH4ATK2hWYjVg',
    appId: '1:229438324185:ios:c69e4a2e801dffaaa4adc8',
    messagingSenderId: '229438324185',
    projectId: 'upkeep-1658b',
    storageBucket: 'upkeep-1658b.appspot.com',
    iosClientId: '229438324185-8jlv18b01jcuvpl9nqqtu03j4rjdhcq4.apps.googleusercontent.com',
    iosBundleId: 'com.example.upkeep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRGZvw4v5FDONPA-s9KACH4ATK2hWYjVg',
    appId: '1:229438324185:ios:c69e4a2e801dffaaa4adc8',
    messagingSenderId: '229438324185',
    projectId: 'upkeep-1658b',
    storageBucket: 'upkeep-1658b.appspot.com',
    iosClientId: '229438324185-8jlv18b01jcuvpl9nqqtu03j4rjdhcq4.apps.googleusercontent.com',
    iosBundleId: 'com.example.upkeep',
  );
}
